name: Discord Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Commit Updates
        uses: Sniddl/discord-commits@v1.8
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          template: "avatar-with-link"
          # This forces it to use your active GitHub profile picture:
          fallback-avatar: "https://github.com{{ github.actor }}.png" 
