name: Discord Push Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Split Native Embed to Discord
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.event.repository.name }}
          BRANCH: ${{ github.ref_name }}
          MESSAGE: ${{ github.event.head_commit.message }}
          SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=$(echo "$SHA" | cut -c1-7)
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d @- \
               "$WEBHOOK_URL" <<EOF
          {
            "username": "$ACTOR",
            "avatar_url": "[github.com](https://github.com/$ACTOR.png)",
            "embeds": [
              {
                "author": {
                  "name": "$ACTOR",
                  "icon_url": "[github.com](https://github.com/$ACTOR.png)"
                },
                "description": "**[$REPO:$BRANCH] 1 new commit**\n\n\`$SHORT_SHA\` $MESSAGE - $ACTOR"
              }
            ]
          }
          EOF
