name: Discord Push Notification

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message Directly to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "username": "SnajperEXE",
                 "avatar_url": "https://githubusercontent.com",
                 "embeds": [
                   {
                     "title": "[${{ github.repository }}] New commit pushed",
                     "color": 2105893,
                     "description": "Changes committed directly via GitHub web interface by ${{ github.actor }}."
                   }
                 ]
               }' \
               ${{ secrets.WEBHOOK_URL }}
